[package]
name = "sapso"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = "3.0"
colorful = "0.3.2"
plotters = "0.3.7"
prettytable = "0.10.0"
rand = "0.8.5"
rayon = "1.10.0"
serde = { version = "1.0.217", features = ["derive"] }
